name: Format Headlamp Check

on: 
  push:
    paths:
      - HeadlampLEDStrip/**

jobs:
  main:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Format
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: "HeadlampLEDStrip"
          extensions: "cpp,h,ino"
          clangFormatVersion: 14
