name: Format Wall Check

on: 
  push:
    paths:
      - WallLEDStrip/**
      - .github/workflows/format-wall-check.yml

jobs:
  main:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Format
        uses: DoozyX/clang-format-lint-action@v0.18.2
        with:
          source: "WallLEDStrip"
          extensions: "cpp,h,ino"
          clangFormatVersion: 14
