name: Format Desk Check

on: 
  push:
    paths:
      - DeskLightLEDStrip/**
      - .github/workflows/format-desk-check.yml

jobs:
  main:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Format
        uses: DoozyX/clang-format-lint-action@v0.18.2
        with:
          source: "DeskLightLEDStrip"
          extensions: "cpp,h,ino"
          clangFormatVersion: 14
